import type { ModelPricingRule } from '@/types/usage';

export const DEFAULT_PRICING_RULES: ModelPricingRule[] = [
  // Anthropic Claude
  {
    modelPattern: 'claude-3-7-sonnet*',
    displayName: 'Claude 3.7 Sonnet',
    provider: 'anthropic',
    inputPricePerMillion: 3.0,
    outputPricePerMillion: 15.0,
    reasoningPricePerMillion: 15.0,
    cacheReadPricePerMillion: 0.3,
    cacheWritePricePerMillion: 3.75,
  },
  {
    modelPattern: 'claude-3-5-sonnet*',
    displayName: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    inputPricePerMillion: 3.0,
    outputPricePerMillion: 15.0,
    reasoningPricePerMillion: 15.0,
    cacheReadPricePerMillion: 0.3,
    cacheWritePricePerMillion: 3.75,
  },
  {
    modelPattern: 'claude-3-5-haiku*',
    displayName: 'Claude 3.5 Haiku',
    provider: 'anthropic',
    inputPricePerMillion: 0.8,
    outputPricePerMillion: 4.0,
    cacheReadPricePerMillion: 0.08,
    cacheWritePricePerMillion: 1.0,
  },
  {
    modelPattern: 'claude-3-opus*',
    displayName: 'Claude 3 Opus',
    provider: 'anthropic',
    inputPricePerMillion: 15.0,
    outputPricePerMillion: 75.0,
    cacheReadPricePerMillion: 1.5,
    cacheWritePricePerMillion: 18.75,
  },
  {
    modelPattern: 'claude-opus-4*',
    displayName: 'Claude Opus 4.x',
    provider: 'anthropic',
    inputPricePerMillion: 5.0,
    outputPricePerMillion: 25.0,
    cacheReadPricePerMillion: 0.5,
    cacheWritePricePerMillion: 6.25,
  },
  {
    modelPattern: 'claude-haiku-4*',
    displayName: 'Claude Haiku 4.x',
    provider: 'anthropic',
    inputPricePerMillion: 1.0,
    outputPricePerMillion: 5.0,
    cacheReadPricePerMillion: 0.1,
    cacheWritePricePerMillion: 1.25,
  },

  // OpenAI
  {
    modelPattern: 'gpt-5.6-sol*',
    displayName: 'GPT-5.6 Sol',
    provider: 'openai',
    inputPricePerMillion: 5.0,
    outputPricePerMillion: 30.0,
    reasoningPricePerMillion: 30.0,
    cacheReadPricePerMillion: 0.5,
    cacheWritePricePerMillion: 6.25,
  },
  {
    modelPattern: 'gpt-5.6-terra*',
    displayName: 'GPT-5.6 Terra',
    provider: 'openai',
    inputPricePerMillion: 2.5,
    outputPricePerMillion: 15.0,
    cacheReadPricePerMillion: 0.25,
    cacheWritePricePerMillion: 3.125,
  },
  {
    modelPattern: 'gpt-5.6-luna*',
    displayName: 'GPT-5.6 Luna',
    provider: 'openai',
    inputPricePerMillion: 1.0,
    outputPricePerMillion: 6.0,
    cacheReadPricePerMillion: 0.1,
    cacheWritePricePerMillion: 1.25,
  },
  {
    modelPattern: 'gpt-4o',
    displayName: 'GPT-4o',
    provider: 'openai',
    inputPricePerMillion: 2.5,
    outputPricePerMillion: 10.0,
    cacheReadPricePerMillion: 1.25,
    cacheWritePricePerMillion: 2.5,
  },
  {
    modelPattern: 'gpt-4o-mini*',
    displayName: 'GPT-4o mini',
    provider: 'openai',
    inputPricePerMillion: 0.15,
    outputPricePerMillion: 0.6,
    cacheReadPricePerMillion: 0.075,
    cacheWritePricePerMillion: 0.15,
  },
  {
    modelPattern: 'o1*',
    displayName: 'OpenAI o1',
    provider: 'openai',
    inputPricePerMillion: 15.0,
    outputPricePerMillion: 60.0,
    reasoningPricePerMillion: 60.0,
    cacheReadPricePerMillion: 7.5,
    cacheWritePricePerMillion: 15.0,
  },
  {
    modelPattern: 'o3-mini*',
    displayName: 'OpenAI o3-mini',
    provider: 'openai',
    inputPricePerMillion: 1.1,
    outputPricePerMillion: 4.4,
    reasoningPricePerMillion: 4.4,
    cacheReadPricePerMillion: 0.55,
    cacheWritePricePerMillion: 1.1,
  },

  // DeepSeek
  {
    modelPattern: 'deepseek-chat*',
    displayName: 'DeepSeek V3 (Chat)',
    provider: 'deepseek',
    inputPricePerMillion: 0.14,
    outputPricePerMillion: 0.28,
    cacheReadPricePerMillion: 0.014,
    cacheWritePricePerMillion: 0.14,
  },
  {
    modelPattern: 'deepseek-reasoner*',
    displayName: 'DeepSeek R1 (Reasoner)',
    provider: 'deepseek',
    inputPricePerMillion: 0.55,
    outputPricePerMillion: 2.19,
    reasoningPricePerMillion: 2.19,
    cacheReadPricePerMillion: 0.14,
    cacheWritePricePerMillion: 0.55,
  },

  // Google Gemini
  {
    modelPattern: 'gemini-2.0-flash*',
    displayName: 'Gemini 2.0 Flash',
    provider: 'gemini',
    inputPricePerMillion: 0.1,
    outputPricePerMillion: 0.4,
    cacheReadPricePerMillion: 0.025,
    cacheWritePricePerMillion: 0.1,
  },
  {
    modelPattern: 'gemini-1.5-pro*',
    displayName: 'Gemini 1.5 Pro',
    provider: 'gemini',
    inputPricePerMillion: 1.25,
    outputPricePerMillion: 5.0,
    cacheReadPricePerMillion: 0.3125,
    cacheWritePricePerMillion: 1.25,
  },
  {
    modelPattern: 'gemini-1.5-flash*',
    displayName: 'Gemini 1.5 Flash',
    provider: 'gemini',
    inputPricePerMillion: 0.075,
    outputPricePerMillion: 0.3,
    cacheReadPricePerMillion: 0.01875,
    cacheWritePricePerMillion: 0.075,
  },
];
